// Registry loader: reads shared/proto/protocols.json (generated by scripts/gen_registry.py
// from the client's Assets/GameAssets/lua/Protocol/generated/*.lua corpus) and registers
// all 1215 protocols into the codec registry.

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { registerProtocol, buildResponseMap, protocolCount, type Protocol } from './codec.js'

const here = dirname(fileURLToPath(import.meta.url))
const raw = JSON.parse(readFileSync(join(here, 'protocols.json'), 'utf8')) as Record<string, Protocol>

for (const p of Object.values(raw)) {
  registerProtocol(p)
}
buildResponseMap()

console.log(`Protocol registry seeded (${protocolCount()} protocols from Lua corpus)`)