#!/usr/bin/env python3
"""DX-DOC: generate docs/protocols.md from shared/proto/protocols.json.

Groups protocols by functional domain (prefix ranges + name keywords) and lists
every Request with its real MessageID, fields, and paired Response.
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROTOS = os.path.join(ROOT, 'shared', 'proto', 'protocols.json')
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'docs', 'protocols.md')

protos = json.load(open(PROTOS, encoding='utf-8'))

DOMAINS = [
    ('Auth / Lifecycle', ['EnterServer', 'EnterGame', 'ExitGame', 'Ping', 'BindPhone', 'SendCodeByPhone', 'QueryUserPhone']),
    ('Role / Profile', ['GetRoleInfo', 'ChangeRoleName', 'ChangeGender', 'ChangeHeadIcon', 'ChangeSign', 'RoleList', 'MultiRoleInfo', 'UploadIP', 'GetServerTimeOffset']),
    ('Battle', ['FightRandomSeed', 'FightResult', 'FightSkip', 'BattleInfo', 'StartPVPBattle', 'Battle']),
    ('Dungeon / Copy / Rogue', ['Copy', 'Rogue', 'Dungeon', 'Explore', 'Granary']),
    ('Maze', ['Maze']),
    ('Tower', ['Tower', 'VipReward']),
    ('Arena', ['Arena']),
    ('Guild / Union', ['Guild', 'Union']),
    ('Chat', ['Chat']),
    ('Mail', ['Mail']),
    ('Friend / Mercenary', ['Friend', 'Mercenary']),
    ('Activity / SignIn / Task', ['Activity', 'SignIn', 'LoginSign', 'Task', 'Bounty', 'CheckIn']),
    ('Market / Shop / Pay', ['Market', 'Shop', 'PlaceOrder', 'CheckOrder', 'SyncOrder', 'Pay', 'Recharge', 'Gift']),
    ('Hero / Bag / Equip / Artifact', ['Hero', 'Bag', 'Equip', 'Artifact', 'Hallows', 'Crystal', 'Formation']),
    ('Wish / Summon / Tavern', ['Wish', 'Summon', 'Tavern']),
    ('GM / Debug', ['HandleGM', 'DropTest', 'Admin']),
    ('RedDot / Guide / Misc', ['RedDot', 'NewerGuide', 'VoidVisitor', 'Community', 'HistoricalArchives', 'CommonNotify', 'Notify']),
]

def domain_of(short):
    for dom, kws in DOMAINS:
        for kw in kws:
            if kw in short:
                return dom
    return 'Other'

def fmt_field(f):
    kind = f['kind']
    if kind == 'OBJ':
        ref = (f.get('ref') or '?').rsplit('.', 1)[-1]
        return f"`{f['name']}` OBJ({ref})"
    if kind in ('LIST', 'ARRAY'):
        ek = f.get('elemKind', '?')
        if ek == 'OBJ':
            ref = (f.get('elemRef') or '?').rsplit('.', 1)[-1]
            return f"`{f['name']}` {kind}(OBJ({ref}))"
        return f"`{f['name']}` {kind}({ek})"
    if kind == 'MAP':
        kk, vk = f.get('keyKind', '?'), f.get('valKind', '?')
        if vk == 'OBJ':
            ref = (f.get('valRef') or '?').rsplit('.', 1)[-1]
            return f"`{f['name']}` MAP({kk}, OBJ({ref}))"
        if vk in ('LIST', 'MAP'):
            return f"`{f['name']}` MAP({kk}, {vk})"
        return f"`{f['name']}` MAP({kk}, {vk})"
    return f"`{f['name']}` {kind}"

by_short = {}
for full, p in protos.items():
    by_short.setdefault(p['shortName'], []).append(full)

groups = {d[0]: [] for d in DOMAINS}
groups['Other'] = []
for full, p in protos.items():
    sn = p['shortName']
    if not (sn.startswith('Client') and sn.endswith('Request')) and sn not in ('ClientPing',):
        continue
    if sn.endswith('Notify') or 'Notify' in sn:
        pass  # notifies go to misc via keyword
    groups[domain_of(sn)].append((sn, p))

lines = []
lines.append('# Protocol Reference (generated)')
lines.append('')
lines.append('> Generated by `scripts/gen_protocol_doc.py` from `shared/proto/protocols.json`,')
lines.append('> which is generated by `scripts/gen_registry.py` from the client Lua corpus')
lines.append('> (`Assets/GameAssets/lua/Protocol/generated/*.lua`). **Do not edit by hand.**')
lines.append('')
lines.append(f'Total protocols in corpus: **{len(protos)}** (requests, responses, notifies, DTOs).')
lines.append('')
lines.append('Wire format (verified against decompiled DeepCore.dll):')
lines.append('')
lines.append('- Integers little-endian: S32=4B, S64=8B, S16=2B, F32/F64 IEEE754')
lines.append('- UTF = S16 charCount + UTF-16LE bytes (-1=null, 0=empty)')
lines.append('- Bool/U8/Enum8 = 1 byte; DateTime = S64 (.NET ToBinary); TimeSpan = U64 ms')
lines.append('- OBJ = S32 messageID + fields (-1 = null)')
lines.append('- LIST/ARRAY = S32 count + elements (-1 = null); MAP = S32 count + k/v pairs (-1 = null)')
lines.append('- VS32/VS64 == S32/S64 (client factory has USE_VLQ=false)')
lines.append('- TCP frame: `[type|mask<<4][3B LE length][body]`; PKG_MESSAGE body =')
lines.append('  `[msgType u8][sendId u32 (not for NOTIFY)][route s32][payload]`')
lines.append('- Requests carry `c2s_requestId` (from base ClientRequest) unless parent is DeepCore.Protocol.Request')
lines.append('- Responses always start: `s2c_code S32, s2c_msg UTF, InnerResponse OBJ, s2c_notifys LIST(Notify)`')
lines.append('')

for dom in [d[0] for d in DOMAINS] + ['Other']:
    seen_ids = set()
    entries = []
    for item in sorted(groups.get(dom, []), key=lambda x: x[1]['messageId']):
        if item[1]['messageId'] in seen_ids:
            continue
        seen_ids.add(item[1]['messageId'])
        entries.append(item)
    if not entries:
        continue
    lines.append(f'## {dom} ({len(entries)})')
    lines.append('')
    lines.append('| MessageID | Request | Fields (own, excl. base) | Response |')
    lines.append('|---|---|---|---|')
    for sn, p in entries:
        own = [f for f in p['fields'] if f['name'] != 'c2s_requestId']
        flds = '; '.join(fmt_field(f) for f in own) or '—'
        resp_short = sn[:-7] + 'Response' if sn.endswith('Request') else None
        resp_id = ''
        if resp_short and resp_short in by_short:
            resp_id = f'0x{protos[by_short[resp_short][0]]["messageId"]:08X}'
        lines.append(f'| 0x{p["messageId"]:08X} | {sn} | {flds} | {resp_id} |')
    lines.append('')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w', encoding='utf-8').write('\n'.join(lines))
n_req = sum(len(v) for v in groups.values())
print(f'wrote {OUT}: {n_req} request protocols documented across {len(DOMAINS)+1} domains')
